# Generated by Django 5.0.2 on 2024-03-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Uni_ID',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
